[theme]
theme = "nord-dark"
[icons]
icons = "awesome6"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
[[block.click]]
button = "left"
cmd = "alacritty -e ranger"

[[block]]
block = "memory"
[block.theme_overrides]
idle_bg = "#226310"
idle_fg = "#abcdef"

[[block]]
block = "cpu"
interval = 1
format = " $icon $utilization "
[block.theme_overrides]
idle_bg = "#123456"
idle_fg = "#abcdef"
[[block.click]]
button = "left"
cmd = "alacritty -e htop"

[[block]]
block = "sound"
[block.theme_overrides]
idle_bg = "#4c492a"
idle_fg = "#abcdef"
[[block.click]]
button = "left"
cmd = "alacritty -e alsamixer"

[[block]]
block = "net"
format = " $ip  $speed_down "
[block.theme_overrides]
idle_bg = "#165042"
idle_fg = "#abcdef"
[[block.click]]
button = "left"
cmd = "alacritty -e ping 8.8.8.8"

[[block]]
block = "time"
interval = 60
[block.format]
full = " $timestamp.datetime(f:'%R', l:fr_BE) "
[block.theme_overrides]
idle_bg = "#330085"
idle_fg = "#abcdef"
[[block.click]]
button = "left"
cmd = "alacritty -e ~/.config/i3status-rust/click_time.sh &"
